const notationTables = {
  toFlat: {
    'A♭': 'A♭',
    'A♯': 'B♭',
    A: 'A',
    'B♭': 'B♭',
    'B♯': 'C',
    B: 'B',
    'C♭': 'B',
    'C♯': 'D♭',
    C: 'C',
    'D♭': 'D♭',
    'D♯': 'E♭',
    D: 'D',
    'E♭': 'E♭',
    'E♯': 'F',
    E: 'E',
    'F♭': 'E',
    'F♯': 'G♭',
    F: 'F',
    'G♭': 'G♭',
    'G♯': 'A♭',
    G: 'G',
  },
  toSharp: {
    'A♭': 'G♯',
    'A♯': 'A♯',
    A: 'A',
    'B♭': 'A♯',
    'B♯': 'C',
    B: 'B',
    'C♭': 'B',
    'C♯': 'C♯',
    C: 'C',
    'D♭': 'C♯',
    'D♯': 'D♯',
    D: 'D',
    'E♭': 'D♯',
    'E♯': 'F',
    E: 'E',
    'F♭': 'E',
    'F♯': 'F♯',
    F: 'F',
    'G♭': 'F♯',
    'G♯': 'G♯',
    G: 'G',
  },
};
export default notationTables;
